create table if not exists endpoint_hits
(
    id        bigint generated by default as identity primary key,
    app       varchar(255),
    uri       varchar(255),
    ip        varchar(15),
    timestamp timestamp without time zone
);

